version: 2

models:
  - name: stg_executions
    description: "証券取引データのクレンジング済みモデル"
    columns:
      - name: execution_id
        description: "取引のユニークID"
        tests:
          - not_null
          - unique

      - name: account_id
        tests:
          - not_null

      - name: trade_type
        description: "売買区分"
        tests:
          - accepted_values:
              values: ['BUY', 'SELL'] 