version: 2

models:
  # --- 国内現物取引 ---
  - name: stg_stock_cash_orders
    description: "国内現物注文のStagingモデル。ハッシュキーの生成とデータ型の統一。"
    columns:
      - name: order_hk
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - not_null

  - name: stg_stock_cash_executions
    description: "国内現物約定のStagingモデル。注文データとのリレーションを検証。"
    columns:
      - name: execution_hk
        tests:
          - unique
          - not_null
      - name: order_hk
        tests:
          - not_null
          # 注文Stagingに親レコードが存在することを確認
          - relationships:
              to: ref('stg_stock_cash_orders')
              field: order_hk

  # --- 外国株取引 ---
  - name: stg_foreign_stock_executions
    description: "外国株約定のStagingモデル。通貨コードの存在チェックを含む。"
    columns:
      - name: execution_hk
        tests:
          - unique
          - not_null
      - name: currency_code
        tests:
          - accepted_values:
              values: ['USD', 'HKD', 'JPY']

  # --- 顧客・共通 ---
  - name: stg_customer_profiles
    description: "顧客マスタのStagingモデル。口座IDの重複をチェック。"
    columns:
      - name: account_hk
        tests:
          - unique
          - not_null
      - name: account_id
        tests:
          - not_null

  - name: stg_cash_transactions
    description: "入出金明細のStagingモデル。"
    columns:
      - name: transaction_hk
        tests:
          - unique
          - not_null
      - name: amount
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0  -- マイナスの場合はtransaction_typeで制御する運用を想定