-- 2-1. DDL: 外国株式約定リンク
CREATE OR REPLACE TABLE SBI_RAW_VAULT.LINK_FOREIGN_EXECUTION_ACCOUNT (
    EXEC_FOREIGN_ACCOUNT_LK BINARY(64) NOT NULL PRIMARY KEY,
    EXECUTION_HK BINARY(64) NOT NULL,
    ACCOUNT_HK BINARY(64) NOT NULL,
    BRAND_HK BINARY(64) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ(9),
    RECORD_SOURCE VARCHAR(100)
) COMMENT = 'リンク：外国株式の約定と口座・銘柄の紐付け';

-- 2-2. INSERT: リンクのロード
INSERT INTO SBI_RAW_VAULT.LINK_FOREIGN_EXECUTION_ACCOUNT
SELECT 
    SHA2_BINARY(CONCAT_WS('|', COALESCE(CAST(EXECUTION_HK AS STRING), ''), COALESCE(CAST(ACCOUNT_HK AS STRING), ''), COALESCE(CAST(BRAND_HK AS STRING), '')), 256),
    EXECUTION_HK,
    ACCOUNT_HK,
    BRAND_HK,
    CURRENT_TIMESTAMP(),
    RECORD_SOURCE
FROM SBI_STAGING.stg_foreign_exec_test src
WHERE NOT EXISTS (
    SELECT 1 FROM SBI_RAW_VAULT.LINK_FOREIGN_EXECUTION_ACCOUNT tgt 
    WHERE SHA2_BINARY(CONCAT_WS('|', COALESCE(CAST(src.EXECUTION_HK AS STRING), ''), COALESCE(CAST(src.ACCOUNT_HK AS STRING), ''), COALESCE(CAST(src.BRAND_HK AS STRING), '')), 256) = tgt.EXEC_FOREIGN_ACCOUNT_LK
)
QUALIFY ROW_NUMBER() OVER (PARTITION BY EXECUTION_HK, ACCOUNT_HK, BRAND_HK ORDER BY LOAD_DATE ASC) = 1;