-- 国内信用建玉固有属性サテライト
CREATE OR REPLACE TABLE SBI_RAW_VAULT.SAT_POS_DOMESTIC_MARGIN (
    ACCOUNT_POSITION_LK BINARY(64) NOT NULL COMMENT 'リンクハッシュキー',
    POSITION_HASHDIFF BINARY(64) NOT NULL COMMENT '属性ハッシュ差分',
    LOAD_DATE TIMESTAMP_NTZ(9) NOT NULL COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース',
    PAYMENT_MARKET VARCHAR(20) COMMENT '決済市場',
    
    PRIMARY KEY (ACCOUNT_POSITION_LK, LOAD_DATE)
) COMMENT = '残高サテライト：国内信用固有の属性（決済市場等）を管理';