-- 外国証券約定明細ステージング
CREATE OR REPLACE TABLE sbi_staging.stg_foreign_stock_test (
    -- Data Vault用ハッシュキー
    EXECUTION_HK BINARY(64) COMMENT '取引番号ベースの約定HK',
    ACCOUNT_HK BINARY(64) COMMENT '店番口座ベースの口座HK',
    BRAND_HK BINARY(64) COMMENT '銘柄（証券コード）ベースの銘柄HK',
    
    -- 元データ項目
    TRADE_DATE VARCHAR(8) COMMENT '国内約定日(YYYYMMDD)',
    MKDB_ID VARCHAR(11) COMMENT '店番口座番号',
    SECURITIES_CODE VARCHAR(20) COMMENT '銘柄（証券）コード',
    PRODUCT_CODE VARCHAR(10) COMMENT '商品コード(81:外国株式等)',
    BUY_SELL_CODE VARCHAR(1) COMMENT '売買コード(1:売却 3:買付)',
    AUTO_ORDER_TYPE_CODE VARCHAR(10) COMMENT '自動注文種別(2:定期買付)',
    SEC_TRADE_COUNTRY_CODE VARCHAR(10) COMMENT '証券取引国コード(304:米国等)',
    SPECIFIC_ACCOUNT_TYPE VARCHAR(10) COMMENT '特定口座区分(預り区分判定用)',
    SETTLEMENT_TYPE VARCHAR(10) COMMENT '決済種別(1:円貨 2:外貨)',
    CHANNEL_CODE VARCHAR(10) COMMENT 'チャネルコード(取引チャネル判定用)',
    CORRECTION_TYPE VARCHAR(1) COMMENT '訂正区分(0:未取消)',
    TRANSACTION_NO VARCHAR(20) COMMENT '取引番号',
    TAX_B_CCY_GROSS_AMOUNT NUMBER(19,4) COMMENT '課税前国内通貨約定金額（円貨）',
    
    -- メタデータ
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE VARCHAR(100)
) COMMENT = '外国証券約定明細：ステージング';

-- 外国証券約定明細ステージング データロード用ビュー
-- 約定テストデータ 10万件
INSERT INTO sbi_staging.stg_foreign_stock_test
SELECT 
    SHA2_BINARY(CONCAT_WS('|', '304', LPAD(SEQ8(), 10, '0')), 256) as EXECUTION_HK,
    SHA2_BINARY(LPAD(MOD(ABS(RANDOM()), 100000), 11, '0'), 256) as ACCOUNT_HK,
    SHA2_BINARY(CASE WHEN MOD(ABS(RANDOM()), 2) = 0 THEN 'AAPL' ELSE 'VTI' END, 256) as BRAND_HK,
    '202504' || LPAD(MOD(ABS(RANDOM()), 30) + 1, 2, '0') as TRADE_DATE,
    LPAD(MOD(ABS(RANDOM()), 100000), 11, '0') as MKDB_ID,
    CASE WHEN MOD(ABS(RANDOM()), 2) = 0 THEN 'AAPL' ELSE 'VTI' END as SECURITIES_CODE,
    '81' as PRODUCT_CODE,
    CASE WHEN MOD(ABS(RANDOM()), 3) = 0 THEN '1' ELSE '3' END as BUY_SELL_CODE,
    CASE WHEN MOD(ABS(RANDOM()), 5) = 0 THEN '2' ELSE NULL END as AUTO_ORDER_TYPE_CODE,
    CASE MOD(ABS(RANDOM()), 4) 
        WHEN 0 THEN '304' -- 米国
        WHEN 1 THEN '108' -- 香港
        WHEN 2 THEN '103' -- 韓国
        ELSE '110'        -- ベトナム
    END as SEC_TRADE_COUNTRY_CODE,
    MOD(ABS(RANDOM()), 10) as SPECIFIC_ACCOUNT_TYPE,
    CASE WHEN MOD(ABS(RANDOM()), 2) = 0 THEN '1' ELSE '2' END as SETTLEMENT_TYPE,
    MOD(ABS(RANDOM()), 10) as CHANNEL_CODE,
    '0' as CORRECTION_TYPE,
    LPAD(SEQ8(), 20, '0') as TRANSACTION_NO,
    ROUND(UNIFORM(1000, 1000000, RANDOM()), 0) as TAX_B_CCY_GROSS_AMOUNT,
    CURRENT_TIMESTAMP(),
    'TEST_GEN_FOREIGN_EXE'
FROM TABLE(GENERATOR(ROWCOUNT => 100000));

