
-- 約定明細テスト用テーブルの作成
CREATE OR REPLACE TABLE sbi_staging.stg_st_sec_test (
    execution_hk BINARY(64) NOT NULL COMMENT '約定ハッシュキー（店番口座-約定番号）',
    account_hk BINARY(64) NOT NULL COMMENT '口座ハッシュキー（店番-口座）',
    brand_hk BINARY(64) NOT NULL COMMENT '銘柄ハッシュキー（銘柄コード）',
    theme_hk BINARY(64) NOT NULL COMMENT 'テーマハッシュキー（テーマID）',
    execution_hashdiff BINARY(64) NOT NULL COMMENT '約定属性ハッシュ差分（差分比較用）',
    base_month VARCHAR(6) COMMENT '基準月 (YYYYMM)',
    base_date DATE COMMENT '基準日 (YYYY-MM-DD)',
    buten_kouza VARCHAR COMMENT '店番-口座番号',
    order_id VARCHAR COMMENT '注文ID（店番口座|約定番号）',
    ec_no INT COMMENT '約定番号',
    trade_date VARCHAR COMMENT '取引日 (YYYY-MM-DD)',
    trade_exec_date TIMESTAMP_NTZ COMMENT '取引執行日時',
    trade_seq INT COMMENT '取引連番',
    cancel_flg INT COMMENT '取消フラグ (0:有効, 1:取消)',
    order_type VARCHAR COMMENT '注文種別 (EXEなど)',
    settle_cd VARCHAR COMMENT '決済コード',
    buy_sell VARCHAR COMMENT '売買区分 (1:売, 2:買など)',
    hitokutei_trade_kbn VARCHAR COMMENT '非特定取引区分',
    market_cd VARCHAR COMMENT '市場コード',
    brand_cd VARCHAR(5) COMMENT '銘柄コード',
    brand_name VARCHAR COMMENT '銘柄名',
    commission_flg VARCHAR COMMENT '手数料フラグ',
    route VARCHAR COMMENT '注文経路',
    exec_quantity INT COMMENT '約定数量',
    exec_price INT COMMENT '約定単価',
    exec_amount INT COMMENT '約定金額',
    keijou_quantity INT COMMENT '計上数量',
    keijou_commission INT COMMENT '計上手数料',
    keijou_amount INT COMMENT '計上金額',
    theme_id VARCHAR COMMENT 'テーマID',
    target_date VARCHAR COMMENT '対象日',
    load_date TIMESTAMP_NTZ COMMENT 'ロード日時',
    record_source VARCHAR COMMENT 'レコードソース',
    other_val VARIANT COMMENT 'その他属性（JSON形式）',
    
    PRIMARY KEY (execution_hk)
) COMMENT = '約定明細（テスト用ステージングテーブル）';

--テストデータのロード
INSERT INTO sbi_staging.stg_st_sec_test
SELECT 
    -- ハッシュ生成ロジック (SHA2_BINARY 256の結果をBINARY(64)に格納)
    SHA2_BINARY(concat_ws('|', buten_kouza, coalesce(cast(ec_no as string), '')), 256) as execution_hk,
    SHA2_BINARY(concat_ws('|', coalesce(SPLIT_PART(buten_kouza, '-', 1), ''), coalesce(SPLIT_PART(buten_kouza, '-', 2), '')), 256) as account_hk,
    SHA2_BINARY(coalesce(LPAD(brand_cd, 5, '0'), ''), 256) as brand_hk,
    SHA2_BINARY(coalesce(theme_id, ''), 256) as theme_hk,
    SHA2_BINARY(
        concat_ws('|',
        coalesce(order_type, ''),
        coalesce(settle_cd, ''),
        coalesce(buy_sell, ''),
        coalesce(hitokutei_trade_kbn, ''),
        coalesce(cast(exec_quantity as string), ''),
        coalesce(cast(exec_price as string), ''),
        TO_VARCHAR(trade_exec_date, 'YYYY-MM-DD HH24:MI:SS')), 256) as execution_hashdiff,
    
    -- 基本データ
    base_month,
    TO_DATE(base_date) as base_date,
    buten_kouza,
    concat_ws('|', buten_kouza, coalesce(cast(ec_no as string), '')) as order_id,
    ec_no,
    trade_date,
    trade_exec_date,
    trade_seq,
    cancel_flg,
    order_type,
    settle_cd,
    buy_sell,
    hitokutei_trade_kbn,
    market_cd,
    LPAD(brand_cd, 5, '0') as brand_cd,
    brand_name,
    commission_flg,
    route,
    exec_quantity,
    exec_price,
    exec_amount,
    keijou_quantity,
    keijou_commission,
    keijou_amount,
    theme_id,
    target_date,
    TO_TIMESTAMP_NTZ(trade_date) as load_date,
    'TEST_GEN_ST_SEC' as record_source,
    OBJECT_CONSTRUCT('customer_id', 'CUST-' || LPAD(ec_no, 8, '0'), 'order_id', order_id) as other_val
FROM (
    SELECT 
        '202510' as base_month,
        DATEADD(day, UNIFORM(0, 30, RANDOM()), '2025-10-01') as base_date,
        LPAD(UNIFORM(100, 999, RANDOM()), 3, '0') || '-' || LPAD(UNIFORM(1, 9999999, RANDOM()), 7, '0') as buten_kouza,
        SEQ8() as ec_no,
        base_date::VARCHAR as trade_date,
        -- 日付にランダムな時間を加算
        DATEADD(second, UNIFORM(32400, 54000, RANDOM()), base_date::TIMESTAMP_NTZ) as trade_exec_date,
        UNIFORM(1, 10, RANDOM()) as trade_seq,
        0 as cancel_flg,
        'EXE' as order_type,
        '01' as settle_cd,
        decode(UNIFORM(1, 2, RANDOM()), 1, '1', '2') as buy_sell, -- 1:売, 2:買
        '0' as hitokutei_trade_kbn,
        'T' as market_cd,
        UNIFORM(1000, 9999, RANDOM())::VARCHAR as brand_cd,
        'テスト銘柄_' || brand_cd as brand_name,
        '1' as commission_flg,
        '2' as route,
        UNIFORM(1, 500, RANDOM()) * 100 as exec_quantity,
        UNIFORM(500, 15000, RANDOM()) as exec_price,
        (exec_quantity * exec_price) as exec_amount,
        exec_quantity as keijou_quantity,
        UNIFORM(0, 1000, RANDOM()) as keijou_commission,
        (exec_amount + keijou_commission) as keijou_amount,
        'THEME-' || LPAD(UNIFORM(1, 100, RANDOM()), 3, '0') as theme_id,
        trade_date as target_date
    FROM TABLE(GENERATOR(ROWCOUNT => 100000))
) t;