-- 外国株マスター（ETF判定用）ステージング
CREATE OR REPLACE TABLE SBI_STAGING.stg_foreign_brand_master_test (
    BRAND_HK BINARY(64),
    PRODUCT_CODE VARCHAR(20) COMMENT '銘柄コード',
    SECTOR VARCHAR(20) COMMENT 'セクター(ETF判定用)',
    COUNTRY_CODE VARCHAR(10) COMMENT '国コード(US等)',
    STATUS VARCHAR(1) COMMENT 'ステータス(9以外が有効)',
    
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_SOURCE VARCHAR(100)
) COMMENT = '外国株マスター：米国ETF判定用属性';

-- マスターテストデータ（AAPLとVTI）
INSERT INTO SBI_STAGING.stg_foreign_brand_master_test
SELECT SHA2_BINARY('AAPL', 256), 'AAPL', 'Technology', 'US', '0', CURRENT_TIMESTAMP(), 'TEST_MASTER'
UNION ALL
SELECT SHA2_BINARY('VTI', 256), 'VTI', 'ETF', 'US', '0', CURRENT_TIMESTAMP(), 'TEST_MASTER';