-- テーマハブテーブル（HUB_THEME）の定義
CREATE OR REPLACE TABLE SBI_RAW_VAULT.HUB_THEME (
    THEME_HK BINARY(64) NOT NULL COMMENT 'テーマハッシュキー',
    THEME_ID VARCHAR(10) NOT NULL COMMENT 'テーマID（ビジネスキー）',
    LOAD_DATE TIMESTAMP_NTZ(9) COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース', -- 18から100へ拡張
    
    PRIMARY KEY (THEME_HK)
) COMMENT = 'テーマハブ：投資テーマ情報を一元管理';