-- 注文・口座・銘柄紐付けリンク（LINK_ORDER_ACOUNT）の定義
CREATE OR REPLACE TABLE SBI_RAW_VAULT.LINK_ORDER_ACOUNT (
    ORDER_ACCOUNT_LK BINARY(64) NOT NULL COMMENT 'リンクハッシュキー（注文HK-口座HK-銘柄HK）',
    ORDER_HK BINARY(64) NOT NULL COMMENT '注文ハッシュキー',
    ACCOUNT_HK BINARY(64) NOT NULL COMMENT '口座ハッシュキー',
    BRAND_HK BINARY(64) NOT NULL COMMENT '銘柄ハッシュキー',
    LOAD_DATE TIMESTAMP_NTZ(9) COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース', -- 25から100へ拡張
    
    PRIMARY KEY (ORDER_ACCOUNT_LK),
    -- 各Hubとの参照整合性制約（オプション）
    FOREIGN KEY (ORDER_HK) REFERENCES SBI_RAW_VAULT.HUB_ORDER(ORDER_HK),
    FOREIGN KEY (ACCOUNT_HK) REFERENCES SBI_RAW_VAULT.HUB_ACCOUNT(ACCOUNT_HK),
    FOREIGN KEY (BRAND_HK) REFERENCES SBI_RAW_VAULT.HUB_BRAND(BRAND_HK)
) COMMENT = 'リンク：注文情報とそれに関連する口座・銘柄の関係を保持';