-- 口座・残高紐付けリンク（LINK_ACCOUNT_POSITION）の定義
CREATE OR REPLACE TABLE SBI_RAW_VAULT.LINK_ACCOUNT_POSITION (
    ACCOUNT_POSITION_LK BINARY(64) NOT NULL COMMENT 'リンクハッシュキー（口座HK-残高HK）',
    ACCOUNT_HK BINARY(64) NOT NULL COMMENT '口座ハッシュキー',
    POSITION_HK BINARY(64) NOT NULL COMMENT '残高ハッシュキー（現物預り・信用建玉の明細キー）',
    LOAD_DATE TIMESTAMP_NTZ(9) COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース', -- 26から100へ拡張
    
    PRIMARY KEY (ACCOUNT_POSITION_LK),
    -- 各Hubとの参照整合性制約（オプション）
    FOREIGN KEY (ACCOUNT_HK) REFERENCES SBI_RAW_VAULT.HUB_ACCOUNT(ACCOUNT_HK)
) COMMENT = 'リンク：口座と保有資産（現物預り・信用建玉）の対応関係を保持';