-- 約定・口座・銘柄紐付けリンク（LINK_EXECUTION_ACCOUNT）の定義
CREATE OR REPLACE TABLE SBI_RAW_VAULT.LINK_EXECUTION_ACCOUNT (
    EXECUTION_ACCOUNT_LK BINARY(64) NOT NULL COMMENT 'リンクハッシュキー（約定HK-口座HK-銘柄HK）',
    EXECUTION_HK BINARY(64) NOT NULL COMMENT '約定ハッシュキー',
    ACCOUNT_HK BINARY(64) NOT NULL COMMENT '口座ハッシュキー',
    BRAND_HK BINARY(64) NOT NULL COMMENT '銘柄ハッシュキー',
    LOAD_DATE TIMESTAMP_NTZ(9) COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース', -- 18から100へ拡張
    
    PRIMARY KEY (EXECUTION_ACCOUNT_LK),
    -- 各Hubとの参照整合性（オプション）
    FOREIGN KEY (EXECUTION_HK) REFERENCES SBI_RAW_VAULT.HUB_EXECUTION(EXECUTION_HK),
    FOREIGN KEY (ACCOUNT_HK) REFERENCES SBI_RAW_VAULT.HUB_ACCOUNT(ACCOUNT_HK),
    FOREIGN KEY (BRAND_HK) REFERENCES SBI_RAW_VAULT.HUB_BRAND(BRAND_HK)
) COMMENT = 'リンク：約定情報とそれに関連する口座・銘柄の関係を保持';