-- テーマ属性サテライト（詳細情報）
CREATE OR REPLACE TABLE SBI_RAW_VAULT.SAT_THEME_DETAIL (
    THEME_HK BINARY(64) NOT NULL COMMENT 'テーマハッシュキー',
    THEME_HASHDIFF BINARY(64) NOT NULL COMMENT '属性ハッシュ差分',
    THEME_ID VARCHAR(10) COMMENT 'テーマID',
    THEME_REGIST_MONTH VARCHAR(6) COMMENT 'テーマ登録月',
    THEME_NAME VARCHAR(512) COMMENT 'テーマ名',
    LOAD_DATE TIMESTAMP_NTZ(9) NOT NULL COMMENT 'ロード日時', -- LTZからNTZへ統一
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース', -- 27から100へ拡張（エラー対策）
    
    PRIMARY KEY (THEME_HK, LOAD_DATE)
) COMMENT = 'テーマサテライト：投資テーマの登録月や正式名称を管理';