-- 約定国内株属性サテライト
CREATE OR REPLACE TABLE SBI_RAW_VAULT.SAT_EXEC_DOMESTIC (
    EXECUTION_ACCOUNT_LK BINARY(64) NOT NULL COMMENT 'リンクハッシュキー（約定-口座-銘柄）',
    EXECUTION_HASHDIFF BINARY(64) NOT NULL COMMENT '属性ハッシュ差分（国内株属性の変更検知用）',
    LOAD_DATE TIMESTAMP_NTZ(9) NOT NULL COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース', -- 18から100へ拡張
    THEME_HK BINARY(64) COMMENT 'テーマハッシュキー',
    
    PRIMARY KEY (EXECUTION_ACCOUNT_LK, LOAD_DATE)
) COMMENT = '約定サテライト：国内株固有の属性情報を管理';