-- 信用約定固有属性サテライト
CREATE OR REPLACE TABLE SBI_RAW_VAULT.SAT_EXEC_DOMESTIC_MARGIN (
    EXECUTION_ACCOUNT_LK BINARY(64) NOT NULL COMMENT 'リンクハッシュキー',
    EXEC_MARGIN_HASHDIFF BINARY(64) NOT NULL COMMENT '属性ハッシュ差分',
    LOAD_DATE TIMESTAMP_NTZ(9) NOT NULL COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース',
    REPAYMENT_LIMIT VARCHAR(10) COMMENT '弁済期限（制度/一般区分用）',
    
    PRIMARY KEY (EXECUTION_ACCOUNT_LK, LOAD_DATE)
) COMMENT = '約定サテライト：国内信用固有の属性（弁済期限等）を管理';