-- 国内信用注文固有属性サテライト
CREATE OR REPLACE TABLE SBI_RAW_VAULT.SAT_ORDER_DOMESTIC_MARGIN (
    ORDER_ACCOUNT_LK BINARY(64) NOT NULL COMMENT 'リンクハッシュキー',
    ORDER_HASHDIFF BINARY(64) NOT NULL COMMENT '属性ハッシュ差分（信用固有属性用）',
    LOAD_DATE TIMESTAMP_NTZ(9) NOT NULL COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'RECORD_SOURCE',
    LOAN_RATE INT COMMENT '貸借料率',
    GENERAL_MARGIN_ID VARCHAR(20) COMMENT '一般信用識別ID',
    SITEI_ATUKAI_KBN VARCHAR(10) COMMENT '指定扱い区分',
    KINRI_JOUKEN_KBN VARCHAR(10) COMMENT '金利条件区分',
    BACK_LOAN_RATE_ONLY VARCHAR(10) COMMENT '逆日歩のみフラグ',
    LENDING_FEE INT COMMENT '品貸料',
    GROUP_ID VARCHAR(20) COMMENT 'グループID', -- other_valより抽出
    CLASS_CODE VARCHAR(20) COMMENT 'クラスコード', -- other_valより抽出
    
    PRIMARY KEY (ORDER_ACCOUNT_LK, LOAD_DATE)
) COMMENT = '注文サテライト：国内信用注文固有の属性（金利・料率等）を管理';