-- 銘柄属性サテライト
CREATE OR REPLACE TABLE SBI_RAW_VAULT.SAT_BRAND_DETAIL (
    BRAND_HK BINARY(64) NOT NULL COMMENT '銘柄ハッシュキー',
    BRAND_HASHDIFF BINARY(64) NOT NULL COMMENT '属性ハッシュ差分（銘柄情報の変更検知用）',
    LOAD_DATE TIMESTAMP_NTZ(9) NOT NULL COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース',
    BRAND_NAME VARCHAR COMMENT '銘柄名',
    LISTING_MARKET VARCHAR(50) COMMENT '銘柄上場市場',
    MARKET_KBN VARCHAR(50) COMMENT '銘柄東証市場区分',
    SECTOR_33 VARCHAR(50) COMMENT '銘柄業種分類',
    STOCK_ETF_KBN VARCHAR(20) COMMENT '個別株／ETF区分',
    OLD_MOTHERS_KBN VARCHAR(20) COMMENT '旧マザーズ区分',
    
    PRIMARY KEY (BRAND_HK, LOAD_DATE)
) COMMENT = '銘柄サテライト：銘柄名、市場、業種などの属性情報を管理';