USE ROLE FINANCE_ADMIN_ROLE;
USE DATABASE FINANCE_DEMO_DB;
USE WAREHOUSE FINANCE_DEMO_WH;


-- 残高基本属性サテライト（全商品共通）
CREATE OR REPLACE TABLE SBI_RAW_VAULT.SAT_POSITION_CORE (
    ACCOUNT_POSITION_LK BINARY(64) NOT NULL COMMENT 'リンクハッシュキー（口座-残高）',
    POSITION_HASHDIFF BINARY(64) NOT NULL COMMENT '属性ハッシュ差分（CORE属性の変更検知用）',
    LOAD_DATE TIMESTAMP_NTZ(9) NOT NULL COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース',
    BASE_MONTH VARCHAR(6) COMMENT '基準月',
    BASE_DATE DATE COMMENT '基準日',
    POSITION_NO INT COMMENT '明細番号',
    PRICE_MX_REVISE_VALUE INT COMMENT '修正評価単価',
    EXEC_BASE_BALANCE_T1 INT COMMENT '約定ベース残高',
    APPRAISE_AQUIRE_PRICE INT COMMENT '評価取得価額',
    APPRAISE_MARKET_PRICE INT COMMENT '評価時価',
    APPRAISE_PROFIT_LOSS_PRICE INT COMMENT '評価損益額',
    
    PRIMARY KEY (ACCOUNT_POSITION_LK, LOAD_DATE)
) COMMENT = '残高サテライト：現物・信用の共通資産情報を管理';