-- 注文基本属性サテライト（全商品共通）
CREATE OR REPLACE TABLE SBI_RAW_VAULT.SAT_ORDER_CORE (
    ORDER_ACCOUNT_LK BINARY(64) NOT NULL COMMENT 'リンクハッシュキー（注文-口座-銘柄）',
    ORDER_HASHDIFF BINARY(64) NOT NULL COMMENT '属性ハッシュ差分（CORE属性の変更検知用）',
    LOAD_DATE TIMESTAMP_NTZ(9) NOT NULL COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'RECORD_SOURCE',
    BASE_MONTH VARCHAR(6) COMMENT '基準月',
    BASE_DATE DATE COMMENT '基準日',
    ORDER_NO INT COMMENT '注文番号',
    TRADE_DATE DATE COMMENT '取引日',
    CANCEL VARCHAR(10) COMMENT '取消区分', -- VARCHAR(1)から拡張
    SEARCH_TRADE_M_CD VARCHAR(20) COMMENT '検索用取引中分類コード', 
    TRADE_SHORT_NAME2 VARCHAR(100) COMMENT '取引略称2',
    PRICE INT COMMENT '注文単価',
    QUANTITY INT COMMENT '注文数量',
    FEE INT COMMENT '手数料',
    
    PRIMARY KEY (ORDER_ACCOUNT_LK, LOAD_DATE)
) COMMENT = '注文サテライト：現物・信用の共通注文情報を管理';