-- 約定基本属性サテライト（全商品共通）
-- 約定基本属性サテライト（区分値カラム拡張版）
CREATE OR REPLACE TABLE SBI_RAW_VAULT.SAT_EXECUTION_CORE (
    EXECUTION_ACCOUNT_LK BINARY(64) NOT NULL COMMENT 'リンクハッシュキー（約定-口座-銘柄）',
    EXECUTION_HASHDIFF BINARY(64) NOT NULL COMMENT '属性ハッシュ差分',
    LOAD_DATE TIMESTAMP_NTZ(9) NOT NULL COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース',
    BASE_MONTH VARCHAR(6) COMMENT '基準月',
    BASE_DATE DATE COMMENT '基準日',
    TRADE_EXEC_DATE TIMESTAMP_NTZ(9) COMMENT '取引執行日時',
    CANCEL_FLG VARCHAR(10) COMMENT '取消フラグ',            
    ORDER_TYPE VARCHAR(10) COMMENT '注文種別',            
    BUY_SELL VARCHAR(10) COMMENT '売買区分',              
    MARKET_CD VARCHAR(10) COMMENT '市場コード',           
    SETTLE_CD VARCHAR(10) COMMENT '決済コード', 
    HITOKUTEI_TRADE_KBN VARCHAR(10) COMMENT '非特定取引区分', 
    COMMISSION_FLG VARCHAR(10) COMMENT '手数料フラグ', 
    ROUTE VARCHAR(10) COMMENT '注文経路',
    EXEC_QUANTITY INT COMMENT '約定数量',
    EXEC_PRICE INT COMMENT '約定単価',
    EXEC_AMOUNT INT COMMENT '約定金額',
    KEIJOU_QUANTITY INT COMMENT '計上数量',
    KEIJOU_COMMISSION INT COMMENT '計上手数料',
    KEIJOU_AMOUNT INT COMMENT '計上金額',
    
    PRIMARY KEY (EXECUTION_ACCOUNT_LK, LOAD_DATE)
) COMMENT = '約定サテライト：共通基本情報';