-- 国内現物預り固有属性サテライト
CREATE OR REPLACE TABLE SBI_RAW_VAULT.SAT_POS_DOMESTIC_CASH (
    ACCOUNT_POSITION_LK BINARY(64) NOT NULL COMMENT 'リンクハッシュキー',
    POSITION_HASHDIFF BINARY(64) NOT NULL COMMENT '属性ハッシュ差分',
    LOAD_DATE TIMESTAMP_NTZ(9) NOT NULL COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース',
    JNISA_ACCOUNT_KBN VARCHAR(10) COMMENT 'NISA口座区分', -- 桁数に余裕を持たせる
    DEALER_NO VARCHAR(20) COMMENT 'ディーラー番号',
    
    PRIMARY KEY (ACCOUNT_POSITION_LK, LOAD_DATE)
) COMMENT = '残高サテライト：国内現物固有の属性（NISA等）を管理';