USE ROLE FINANCE_ADMIN_ROLE;
USE WAREHOUSE FINANCE_DEMO_WH;
USE DATABASE FINANCE_DEMO_DB;
USE SCHEMA RAW;

SELECT * FROM RAW.STOCK_CASH_EXECUTIONS SAMPLE (10);

SELECT * FROM CORE.HUB_BRAND;
SELECT * FROM STAGING.STG_BRAND_MASTER
order by brand_cd;