USE ROLE FINANCE_ADMIN_ROLE;
USE WAREHOUSE FINANCE_DEMO_WH;
USE DATABASE FINANCE_DEMO_DB;

SELECT * FROM FINANCE_DEMO_DB.CORE.LINK_EXECUTION_ORDER SAMPLE (10);
SELECT * FROM FINANCE_DEMO_DB.CORE.LINK_ORDER_ACCOUNT_STOCK SAMPLE (10);

SELECT * FROM FINANCE_DEMO_DB.CORE.HUB_ACCOUNT SAMPLE (10);
SELECT * FROM FINANCE_DEMO_DB.CORE.HUB_STOCK SAMPLE (10);
SELECT * FROM FINANCE_DEMO_DB.CORE.HUB_ORDER SAMPLE (10);

SELECT * FROM FINANCE_DEMO_DB.CORE.SAT_ACCOUNT_DETAILS SAMPLE (10);
SELECT * FROM FINANCE_DEMO_DB.CORE.SAT_ACCOUNT_STATUS SAMPLE (10);
SELECT * FROM FINANCE_DEMO_DB.CORE.PIT_ACCOUNT_HOLDINGS SAMPLE (10);
