USE ROLE FINANCE_ADMIN_ROLE;
USE WAREHOUSE FINANCE_DEMO_WH;
USE DATABASE FINANCE_DEMO_DB;
USE SCHEMA CORE;

SELECT * FROM CORE.PIT_ACCOUNT SAMPLE (100) 
Where customer_load_date IS NOT NULL ;

SELECT * FROM CORE.SAT_CUSTOMER_DETAILS SAMPLE (100) WHERE account_hk IN (SELECT DISTINCT account_hk FROM CORE.PIT_ACCOUNT SAMPLE (100)
WHERE LOAD_DATE <= '2025-12-28');

SELECT * FROM CORE.SAT_STOCK_CASH_HOLDINGS SAMPLE (100) WHERE account_hk IN (SELECT DISTINCT account_hk FROM CORE.PIT_ACCOUNT SAMPLE (100)
WHERE LOAD_DATE <= '2025-12-28');

SELECT * FROM CORE.FACT_DAILY_HOLDINGS SAMPLE (100);
SELECT * FROM CORE.DIM_ACCOUNT SAMPLE (100);

