USE DATABASE FINANCE_DEMO_DB;
USE SCHEMA CORE;

--DYNAMIC TABLE REFRESH
ALTER DYNAMIC TABLE dim_account REFRESH;
ALTER DYNAMIC TABLE fact_daily_holdings REFRESH;

-- HUB_ACCOUNT
COMMENT ON TABLE HUB_ACCOUNT IS '顧客口座ハブ: 証券口座を一意に識別するハブ';
COMMENT ON COLUMN HUB_ACCOUNT.ACCOUNT_HK IS '口座ハッシュキー（主キー）';
COMMENT ON COLUMN HUB_ACCOUNT.ACCOUNT_ID IS '口座ID（ビジネスキー）';
COMMENT ON COLUMN HUB_ACCOUNT.LOAD_DATE IS 'データロード日時';
COMMENT ON COLUMN HUB_ACCOUNT.RECORD_SOURCE IS 'データ提供元システム';

-- HUB_STOCK
COMMENT ON TABLE HUB_STOCK IS '銘柄ハブ: 国内株および外国株の銘柄を一意に識別するハブ';
COMMENT ON COLUMN HUB_STOCK.STOCK_HK IS '銘柄ハッシュキー（主キー）';
COMMENT ON COLUMN HUB_STOCK.BRAND_CD IS '銘柄コード（ビジネスキー）';

-- HUB_ORDER
COMMENT ON TABLE HUB_ORDER IS '注文ハブ: 取引注文を一意に識別するハブ';
COMMENT ON COLUMN HUB_ORDER.ORDER_HK IS '注文ハッシュキー（主キー）';
COMMENT ON COLUMN HUB_ORDER.ORDER_ID IS '注文ID（ビジネスキー）';

-- HUB_EXECUTION
COMMENT ON TABLE HUB_EXECUTION IS '約定ハブ: 成立した取引約定を一意に識別するハブ';
COMMENT ON COLUMN HUB_EXECUTION.EXECUTION_HK IS '約定ハッシュキー（主キー）';
COMMENT ON COLUMN HUB_EXECUTION.EXECUTION_ID IS '約定ID（ビジネスキー）';


-- LINK_ORDER_EXECUTION
COMMENT ON TABLE LINK_ORDER_EXECUTION IS '注文約定リンク: 注文とそれに対する約定の紐付け（1:N対応）';
COMMENT ON COLUMN LINK_ORDER_EXECUTION.ORDER_EXECUTION_LK IS '注文約定リンクハッシュキー';
COMMENT ON COLUMN LINK_ORDER_EXECUTION.ORDER_HK IS '注文ハッシュキー';
COMMENT ON COLUMN LINK_ORDER_EXECUTION.EXECUTION_HK IS '約定ハッシュキー';

-- LINK_ACCOUNT_STOCK_HOLDING
COMMENT ON TABLE LINK_ACCOUNT_STOCK_HOLDING IS '口座銘柄保有リンク: どの口座がどの銘柄を保有しているかの紐付け';
COMMENT ON COLUMN LINK_ACCOUNT_STOCK_HOLDING.ACCOUNT_STOCK_HOLDING_LK IS '口座銘柄保有リンクハッシュキー';
COMMENT ON COLUMN LINK_ACCOUNT_STOCK_HOLDING.ACCOUNT_HK IS '口座ハッシュキー';
COMMENT ON COLUMN LINK_ACCOUNT_STOCK_HOLDING.STOCK_HK IS '銘柄ハッシュキー';


-- SAT_STOCK_DETAILS
COMMENT ON TABLE SAT_STOCK_DETAILS IS '銘柄属性サテライト: 銘柄名や市場などの属性情報の履歴';
COMMENT ON COLUMN SAT_STOCK_DETAILS.STOCK_HASHDIFF IS '属性変更検知用ハッシュ';
COMMENT ON COLUMN SAT_STOCK_DETAILS.BRAND_NAME IS '銘柄名';
COMMENT ON COLUMN SAT_STOCK_DETAILS.MARKET_NAME IS '上場市場名';
COMMENT ON COLUMN SAT_STOCK_DETAILS.SECTOR_NAME IS '業種名';

-- SAT_STOCK_CASH_HOLDINGS
COMMENT ON TABLE SAT_STOCK_CASH_HOLDINGS IS '現物預りサテライト: 残高数量および取得単価の推移';
COMMENT ON COLUMN SAT_STOCK_CASH_HOLDINGS.HOLDING_HASHDIFF IS '残高変更検知用ハッシュ';
COMMENT ON COLUMN SAT_STOCK_CASH_HOLDINGS.QUANTITY IS '保有数量';
COMMENT ON COLUMN SAT_STOCK_CASH_HOLDINGS.AVERAGE_COST IS '取得単価';
COMMENT ON COLUMN SAT_STOCK_CASH_HOLDINGS.AS_OF_DATE IS '残高基準日';

-- SAT_EXECUTION_DETAILS
COMMENT ON TABLE SAT_EXECUTION_DETAILS IS '約定詳細サテライト: 約定時の数量、価格、通貨などの詳細情報';
COMMENT ON COLUMN SAT_EXECUTION_DETAILS.PRICE IS '約定価格';
COMMENT ON COLUMN SAT_EXECUTION_DETAILS.CURRENCY_CODE IS '通貨コード';

-- LINK_ACCOUNT_TRANSACTION
COMMENT ON TABLE LINK_ACCOUNT_TRANSACTION IS '口座入出金リンク: 顧客口座と入出金トランザクションの紐付け';
COMMENT ON COLUMN LINK_ACCOUNT_TRANSACTION.ACCOUNT_TRANSACTION_LK IS '口座入出金リンクハッシュキー';
COMMENT ON COLUMN LINK_ACCOUNT_TRANSACTION.ACCOUNT_HK IS '口座ハッシュキー';
COMMENT ON COLUMN LINK_ACCOUNT_TRANSACTION.TRANSACTION_HK IS '入出金ハッシュキー';


-- LINK_ORDER_ACCOUNT_STOCK
COMMENT ON TABLE LINK_ORDER_ACCOUNT_STOCK IS '注文・口座・銘柄リンク: どの口座がどの銘柄に対して注文を出したかの紐付け';
COMMENT ON COLUMN LINK_ORDER_ACCOUNT_STOCK.ORDER_ACCOUNT_STOCK_LK IS '注文口座銘柄リンクハッシュキー';
COMMENT ON COLUMN LINK_ORDER_ACCOUNT_STOCK.ORDER_HK IS '注文ハッシュキー';
COMMENT ON COLUMN LINK_ORDER_ACCOUNT_STOCK.ACCOUNT_HK IS '口座ハッシュキー';