-- SEMANTIC.SV_KPI_023_DOMESTIC_STOCK_MARGIN_EXEC_DAILY
CREATE OR REPLACE VIEW SBI_SEMANTIC.SV_KPI_023_DOMESTIC_STOCK_MARGIN_EXEC_DAILY AS
SELECT
    BASE_DATE AS "約定日",
    -- 属性
    MARGIN_TYPE AS "制度／一般／日計り",
    OPEN_CLOSE_KBN AS "新規／決済",
    SETTLE_METHOD AS "決済方法",
    MARKET_NAME AS "約定市場",
    TRADE_CHANNEL AS "取引チャネル",
    STOCK_ETF_KBN AS "個別株／ETF区分",
    -- 基本メトリクス
    COUNT(DISTINCT MKDB_ID) AS "約定口座数",
    SUM(EXEC_COUNT) AS "約定件数",
    SUM(TOTAL_EXEC_AMOUNT) AS "約定売買代金",
    -- 買付（新規）内訳
    COUNT(DISTINCT CASE WHEN BUY_SELL = 'K' THEN MKDB_ID END) AS "買い約定口座数",
    SUM(CASE WHEN BUY_SELL = 'K' THEN EXEC_COUNT ELSE 0 END) AS "買い約定件数",
    SUM(CASE WHEN BUY_SELL = 'K' THEN TOTAL_EXEC_AMOUNT ELSE 0 END) AS "買い約定代金",
    -- 売却（決済）内訳
    COUNT(DISTINCT CASE WHEN BUY_SELL = 'U' THEN MKDB_ID END) AS "売り約定口座数",
    SUM(CASE WHEN BUY_SELL = 'U' THEN EXEC_COUNT ELSE 0 END) AS "売り約定件数",
    SUM(CASE WHEN BUY_SELL = 'U' THEN TOTAL_EXEC_AMOUNT ELSE 0 END) AS "売り約定代金"
FROM SBI_BUSINESS_VAULT.BV_DAILY_MARGIN_EXECUTION_METRICS
GROUP BY 
    BASE_DATE,
    MARGIN_TYPE,
    OPEN_CLOSE_KBN,
    SETTLE_METHOD,
    MARKET_NAME,
    TRADE_CHANNEL,
    STOCK_ETF_KBN;