-- SEMANTIC.SV_KPI_007_DOMESTIC_STOCK_TRADE_DAILY
CREATE OR REPLACE VIEW SBI_SEMANTIC.SV_KPI_007_DOMESTIC_STOCK_TRADE_DAILY AS
SELECT
    BASE_DATE AS "約定日",
    -- 属性（BVでデコード済み）
    UNIT_S_KBN AS "単元株／S株",
    TRADE_TYPE AS "買付／売却",
    STOCK_ETF_KBN AS "個別株／ETF区分",
    OLD_MOTHERS_KBN AS "旧マザーズ区分",
    BRAND_NAME AS "銘柄名",
    -- メトリクス
    COUNT(DISTINCT MKDB_ID) AS "約定口座数",
    SUM(NET_EXEC_COUNT) AS "約定件数",
    SUM(TOTAL_TRADE_AMOUNT) AS "約定売買代金",
    SUM(TOTAL_FEE) AS "委託手数料",
    -- 手数料が発生した口座・件数（分析用）
    COUNT(DISTINCT CASE WHEN TOTAL_FEE > 0 THEN MKDB_ID END) AS "約定口座数_手数料有",
    SUM(CASE WHEN TOTAL_FEE > 0 THEN NET_EXEC_COUNT ELSE 0 END) AS "約定件数_手数料有"
FROM SBI_BUSINESS_VAULT.BV_DAILY_TRADE_HISTORY_SUMMARY
GROUP BY 
    BASE_DATE,
    UNIT_S_KBN,
    TRADE_TYPE,
    STOCK_ETF_KBN,
    OLD_MOTHERS_KBN,
    BRAND_NAME;

SELECT * FROM SBI_SEMANTIC.SV_KPI_007_DOMESTIC_STOCK_TRADE_DAILY;