-- SEMANTIC.SV_KPI_010_DOMESTIC_STOCK_EXEC_DAILY
CREATE OR REPLACE VIEW SBI_SEMANTIC.SV_KPI_010_DOMESTIC_STOCK_EXEC_DAILY AS
SELECT
    BASE_DATE AS "約定日",
    -- 属性（BVでデコード済み）
    UNIT_S_KBN AS "単元株／S株",
    DEPOSIT_KBN AS "預り区分",
    MARKET_NAME AS "約定市場",
    THEME_NAME AS "テーマ名",
    -- メトリクス
    COUNT(DISTINCT MKDB_ID) AS "約定口座数",
    SUM(EXEC_COUNT) AS "約定件数",
    SUM(TOTAL_EXEC_AMOUNT) AS "約定売買代金",
    SUM(TOTAL_FEE) AS "委託手数料"
FROM SBI_BUSINESS_VAULT.BV_DAILY_EXECUTION_METRICS
GROUP BY 
    BASE_DATE,
    UNIT_S_KBN,
    DEPOSIT_KBN,
    MARKET_NAME,
    THEME_NAME;

SELECT * FROM SBI_SEMANTIC.SV_KPI_010_DOMESTIC_STOCK_EXEC_DAILY;