-- 2-1. DDL: 外国株式約定リンク
CREATE OR REPLACE TABLE SBI_RAW_VAULT.LINK_FOREIGN_EXECUTION_ACCOUNT (
    EXEC_FOREIGN_ACCOUNT_LK BINARY(64) NOT NULL PRIMARY KEY,
    EXECUTION_HK BINARY(64) NOT NULL,
    ACCOUNT_HK BINARY(64) NOT NULL,
    BRAND_HK BINARY(64) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ(9),
    RECORD_SOURCE VARCHAR(100)
) COMMENT = 'リンク：外国株式の約定と口座・銘柄の紐付け';