-- 3-1. DDL: 外国株式約定属性サテライト
CREATE OR REPLACE TABLE SBI_RAW_VAULT.SAT_EXEC_FOREIGN_CORE (
    EXEC_FOREIGN_ACCOUNT_LK BINARY(64) NOT NULL,
    EXEC_FOREIGN_HASHDIFF BINARY(64) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ(9) NOT NULL,
    RECORD_SOURCE VARCHAR(100),
    -- KPI 039 属性
    COUNTRY_CODE VARCHAR(10),       -- 国コード
    DEPOSIT_KBN_CODE VARCHAR(10),    -- 預り区分（SPECIFIC_ACCOUNT_TYPE）
    SETTLEMENT_TYPE VARCHAR(10),     -- 決済方法
    CHANNEL_CODE VARCHAR(10),        -- 取引チャネル
    BUY_SELL_CODE VARCHAR(1),        -- 売買コード
    AUTO_ORDER_TYPE VARCHAR(10),     -- 自動注文種別
    AMOUNT_JPY NUMBER(19,4),         -- 円貨約定金額
    
    PRIMARY KEY (EXEC_FOREIGN_ACCOUNT_LK, LOAD_DATE)
) COMMENT = '約定サテライト：外国株式固有の属性情報を管理';

