-- 4-2. INSERT
INSERT INTO SBI_RAW_VAULT.SAT_FOREIGN_BRAND_DETAIL
SELECT 
    BRAND_HK,
    SHA2_BINARY(CONCAT_WS('|', SECTOR, COUNTRY_CODE), 256),
    CURRENT_TIMESTAMP(),
    RECORD_SOURCE,
    SECTOR,
    COUNTRY_CODE
FROM SBI_STAGING.stg_foreign_brand_master_test
QUALIFY ROW_NUMBER() OVER (PARTITION BY BRAND_HK ORDER BY LOAD_DATE DESC) = 1;