-- 3-2. INSERT: サテライトのロード
INSERT INTO SBI_RAW_VAULT.SAT_EXEC_FOREIGN_CORE
SELECT 
    SHA2_BINARY(CONCAT_WS('|', COALESCE(CAST(EXECUTION_HK AS STRING), ''), COALESCE(CAST(ACCOUNT_HK AS STRING), ''), COALESCE(CAST(BRAND_HK AS STRING), '')), 256),
    SHA2_BINARY(CONCAT_WS('|', SEC_TRADE_COUNTRY_CODE, SPECIFIC_ACCOUNT_TYPE, SETTLEMENT_TYPE, CHANNEL_CODE, BUY_SELL_CODE, TAX_B_CCY_GROSS_AMOUNT), 256),
    CURRENT_TIMESTAMP(),
    RECORD_SOURCE,
    SEC_TRADE_COUNTRY_CODE,
    SPECIFIC_ACCOUNT_TYPE,
    SETTLEMENT_TYPE,
    CHANNEL_CODE,
    BUY_SELL_CODE,
    AUTO_ORDER_TYPE_CODE,
    TAX_B_CCY_GROSS_AMOUNT
FROM SBI_STAGING.stg_foreign_exec_test
QUALIFY ROW_NUMBER() OVER (PARTITION BY EXECUTION_HK ORDER BY LOAD_DATE DESC) = 1;