name: finance_demo_dbt
version: 1.0.0
config-version: 2
profile: finance_demo_dbt
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  finance_demo_dbt:
    staging:
      +schema: STAGING
      +materialized: view
    core:
      +schema: CORE
      +materialized: table
    semantic:
      +schema: SEMANTIC
      +materialized: View
      

