name: USER_24_PUBLIC_SF_FINANCE_DEMO_GIT
version: 1.0.0
config-version: 2
profile: USER_24_PUBLIC_SF_FINANCE_DEMO_GIT
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  USER_24_PUBLIC_SF_FINANCE_DEMO_GIT:
    +materialized: view
