--① テーブルごとの件数確認（一括）
SELECT 'HUB_ACCOUNT' as tbl, count(*) as cnt FROM SBI_RAW_VAULT.HUB_ACCOUNT
UNION ALL SELECT 'HUB_BRAND', count(*) FROM SBI_RAW_VAULT.HUB_BRAND
UNION ALL SELECT 'LINK_ORDER_ACOUNT', count(*) FROM SBI_RAW_VAULT.LINK_ORDER_ACOUNT
UNION ALL SELECT 'SAT_EXECUTION_CORE', count(*) FROM SBI_RAW_VAULT.SAT_EXECUTION_CORE;

--② ハッシュキーの不一致確認（Orphan Check）
-- LINK_ORDER_ACOUNTにあるACCOUNT_HKがHUB_ACCOUNTに存在するか
SELECT count(*) 
FROM SBI_RAW_VAULT.LINK_ORDER_ACOUNT L
LEFT JOIN SBI_RAW_VAULT.HUB_ACCOUNT H ON L.ACCOUNT_HK = H.ACCOUNT_HK
WHERE H.ACCOUNT_HK IS NULL;

--③ 属性情報の紐付け確認（JOINテスト）
SELECT 
    T.THEME_NAME,
    COUNT(*) as EXEC_COUNT,
    SUM(S.EXEC_AMOUNT) as TOTAL_AMOUNT
FROM SBI_RAW_VAULT.SAT_THEME_DETAIL T
INNER JOIN SBI_RAW_VAULT.SAT_EXEC_DOMESTIC D ON T.THEME_HK = D.THEME_HK
INNER JOIN SBI_RAW_VAULT.SAT_EXECUTION_CORE S ON D.EXECUTION_ACCOUNT_LK = S.EXECUTION_ACCOUNT_LK
GROUP BY 1;