INSERT INTO SBI_RAW_VAULT.HUB_EXECUTION (
    EXECUTION_HK,
    BUTEN_KOUZA,
    EC_NO,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT 
    EXECUTION_HK,
    BUTEN_KOUZA,
    EC_NO,
    LOAD_DATE,
    RECORD_SOURCE
FROM (
    -- 1. 国内株式現物約定明細
SELECT EXECUTION_HK, BUTEN_KOUZA, EC_NO, CURRENT_TIMESTAMP() as LOAD_DATE, RECORD_SOURCE FROM sbi_staging.stg_st_sec_test
UNION
    -- 2. 外国株式現物約定明細
SELECT EXECUTION_HK, BUTEN_KOUZA, EC_NO, CURRENT_TIMESTAMP() as LOAD_DATE, RECORD_SOURCE FROM sbi_staging.stg_foreign_stock_test
) src
WHERE NOT EXISTS (
    -- 既にHUBに登録済みの約定キーは除外
    SELECT 1 FROM SBI_RAW_VAULT.HUB_EXECUTION tgt
    WHERE src.EXECUTION_HK = tgt.EXECUTION_HK
)
-- STG側で重複がある場合に備え、キーごとに1件に絞り込む
QUALIFY ROW_NUMBER() OVER (PARTITION BY EXECUTION_HK ORDER BY LOAD_DATE ASC) = 1;