CREATE OR REPLACE DYNAMIC TABLE SBI_RAW_VAULT.PIT_EXECUTION_DAILY
TARGET_LAG = 'DOWNSTREAM'
WAREHOUSE = FINANCE_DEMO_WH
AS
SELECT
    L.EXECUTION_ACCOUNT_LK,
    SD.SNAPSHOT_DATE,
    -- 現物・共通属性ポインタ
    MAX(S_C.LOAD_DATE) AS SAT_EXEC_CORE_LD,
    -- 銘柄詳細ポインタ
    MAX(S_B.LOAD_DATE) AS SAT_BRD_DET_LD,
    -- テーマポインタ
    MAX(S_T.LOAD_DATE) AS SAT_THE_DET_LD,
    -- 信用属性ポインタ
    MAX(S_M.LOAD_DATE) AS SAT_EXEC_MAR_LD
FROM (SELECT DISTINCT SNAPSHOT_DATE FROM SBI_RAW_VAULT.CONTROL_SNAPSHOT_DATES) SD
CROSS JOIN SBI_RAW_VAULT.LINK_EXECUTION_ACCOUNT L
-- 各サテライトとの左外結合（スナップショット時点以前の最新レコードを特定）
LEFT JOIN SBI_RAW_VAULT.SAT_EXECUTION_CORE S_C 
    ON L.EXECUTION_ACCOUNT_LK = S_C.EXECUTION_ACCOUNT_LK AND S_C.LOAD_DATE <= SD.SNAPSHOT_DATE
LEFT JOIN SBI_RAW_VAULT.SAT_BRAND_DETAIL S_B 
    ON L.BRAND_HK = S_B.BRAND_HK AND S_B.LOAD_DATE <= SD.SNAPSHOT_DATE
LEFT JOIN SBI_RAW_VAULT.SAT_THEME_DETAIL S_T 
    ON L.BRAND_HK = S_T.THEME_HK AND S_T.LOAD_DATE <= SD.SNAPSHOT_DATE
LEFT JOIN SBI_RAW_VAULT.SAT_EXEC_DOMESTIC_MARGIN S_M 
    ON L.EXECUTION_ACCOUNT_LK = S_M.EXECUTION_ACCOUNT_LK AND S_M.LOAD_DATE <= SD.SNAPSHOT_DATE
GROUP BY 1, 2;