CREATE OR REPLACE DYNAMIC TABLE SBI_RAW_VAULT.PIT_POSITION_DOMESTIC_DAILY
TARGET_LAG = 'DOWNSTREAM'
WAREHOUSE = FINANCE_DEMO_WH
COMMENT = '国内株残高：特定日時点の属性ポインタを管理するPIT'
AS
SELECT
    L.ACCOUNT_POSITION_LK,
    SD.SNAPSHOT_DATE,
    -- 残高コア属性（数量、取得単価など）
    MAX(S_P.LOAD_DATE) AS SAT_POS_CORE_LD,
    -- 銘柄詳細
    MAX(S_B.LOAD_DATE) AS SAT_BRD_DET_LD
FROM SBI_RAW_VAULT.CONTROL_SNAPSHOT_DATES SD
CROSS JOIN SBI_RAW_VAULT.LINK_ACCOUNT_POSITION L
LEFT JOIN SBI_RAW_VAULT.SAT_POSITION_CORE S_P 
    ON L.ACCOUNT_POSITION_LK = S_P.ACCOUNT_POSITION_LK 
    AND S_P.LOAD_DATE <= SD.SNAPSHOT_DATE
LEFT JOIN SBI_RAW_VAULT.SAT_BRAND_DETAIL S_B 
    ON L.BRAND_HK = S_B.BRAND_HK 
    AND S_B.LOAD_DATE <= SD.SNAPSHOT_DATE
GROUP BY 1, 2;

