CREATE OR REPLACE DYNAMIC TABLE SBI_RAW_VAULT.PIT_ORDER_DAILY
TARGET_LAG = 'DOWNSTREAM'
WAREHOUSE = FINANCE_DEMO_WH
COMMENT = '注文・銘柄情報を高速に横断参照するためのPITテーブル（動的テーブル版）'
AS
SELECT
    L.ORDER_ACCOUNT_LK,
    SD.SNAPSHOT_DATE,
    -- 注文共通属性ポインタ
    MAX(S_O.LOAD_DATE) AS SAT_ORD_CORE_LD,
    -- 信用固有属性ポインタ (SAT_ORDER_DOMESTIC_MARGINを想定)
    MAX(S_M.LOAD_DATE) AS SAT_ORD_MAR_LD,
    -- 銘柄詳細ポインタ
    MAX(S_B.LOAD_DATE) AS SAT_BRD_DET_LD
FROM SBI_RAW_VAULT.CONTROL_SNAPSHOT_DATES SD
CROSS JOIN SBI_RAW_VAULT.LINK_ORDER_ACOUNT L
-- 注文共通サテライトとの結合
LEFT JOIN SBI_RAW_VAULT.SAT_ORDER_CORE S_O 
    ON L.ORDER_ACCOUNT_LK = S_O.ORDER_ACCOUNT_LK 
    AND S_O.LOAD_DATE <= SD.SNAPSHOT_DATE
-- 信用固有サテライトとの結合
LEFT JOIN SBI_RAW_VAULT.SAT_ORDER_DOMESTIC_MARGIN S_M 
    ON L.ORDER_ACCOUNT_LK = S_M.ORDER_ACCOUNT_LK 
    AND S_M.LOAD_DATE <= SD.SNAPSHOT_DATE
-- 銘柄詳細サテライトとの結合
LEFT JOIN SBI_RAW_VAULT.SAT_BRAND_DETAIL S_B 
    ON L.BRAND_HK = S_B.BRAND_HK 
    AND S_B.LOAD_DATE <= SD.SNAPSHOT_DATE
GROUP BY 1, 2;