CREATE OR REPLACE DYNAMIC TABLE SBI_BUSINESS_VAULT.BRDG_DOMESTIC_ST_EXECUTION
TARGET_LAG = 'DOWNSTREAM'
WAREHOUSE = FINANCE_DEMO_WH
AS
SELECT 
    -- データ型エラーを回避するための明示的キャスト
    SHA2_BINARY(CONCAT_WS('|', 
        TO_VARCHAR(P.SNAPSHOT_DATE), 
        BASE64_ENCODE(L.EXECUTION_ACCOUNT_LK)
    ), 256) AS EXEC_SUMMARY_HK,
    L.EXECUTION_ACCOUNT_LK,
    L.ACCOUNT_HK,
    L.BRAND_HK,
    P.SNAPSHOT_DATE AS BASE_DATE,
    -- 信用・現物の取引区分判定
    CASE WHEN P.SAT_EXEC_MAR_LD IS NOT NULL THEN '信用' ELSE '現物' END AS TRADE_TYPE,
    -- サテライトポインタの保持
    P.SAT_EXEC_CORE_LD,
    P.SAT_EXEC_MAR_LD,
    P.SAT_BRD_DET_LD
FROM SBI_RAW_VAULT.PIT_EXECUTION_DAILY P
JOIN SBI_RAW_VAULT.LINK_EXECUTION_ACCOUNT L ON P.EXECUTION_ACCOUNT_LK = L.EXECUTION_ACCOUNT_LK;