CREATE OR REPLACE DYNAMIC TABLE SBI_BUSINESS_VAULT.BRDG_DOMESTIC_ST_POSITION
TARGET_LAG = 'DOWNSTREAM'
WAREHOUSE = FINANCE_DEMO_WH
COMMENT = '国内株残高：分析用にハブ・リンク・サテライトを統合したBridge'
AS
SELECT 
    -- SHA2_BINARY内の型不一致エラーを回避するキャスト
    SHA2_BINARY(CONCAT_WS('|', 
        TO_VARCHAR(P.SNAPSHOT_DATE), 
        BASE64_ENCODE(L.ACCOUNT_POSITION_LK)
    ), 256) AS POS_SUMMARY_HK,
    
    L.ACCOUNT_POSITION_LK,
    L.ACCOUNT_HK,
    L.BRAND_HK,
    P.SNAPSHOT_DATE AS AS_OF_DATE,
    
    -- サテライトへの最新ポインタ（これを使ってBV層で属性を紐付け）
    P.SAT_POS_CORE_LD,
    P.SAT_BRD_DET_LD
FROM SBI_RAW_VAULT.PIT_POSITION_DOMESTIC_DAILY P
JOIN SBI_RAW_VAULT.LINK_ACCOUNT_POSITION L ON P.ACCOUNT_POSITION_LK = L.ACCOUNT_POSITION_LK;