CREATE OR REPLACE DYNAMIC TABLE SBI_BUSINESS_VAULT.BV_DAILY_EXECUTION_METRICS
TARGET_LAG = 'DOWNSTREAM'
WAREHOUSE = FINANCE_DEMO_WH
COMMENT = '日次約定実績メトリクス（統合PIT対応版）'
AS
SELECT
    -- ハッシュキー生成（型エラー回避のためTO_VARCHARを使用）
    SHA2_BINARY(CONCAT_WS('|', TO_VARCHAR(P.SNAPSHOT_DATE), H_E.BUTEN_KOUZA, H_B.BRAND_CD), 256) AS BV_SUMMARY_HK,
    P.SNAPSHOT_DATE AS BASE_DATE,
    H_E.BUTEN_KOUZA AS MKDB_ID,
    H_B.BRAND_CD AS BRAND_CD,
    
    -- 【属性デコード】
    CASE WHEN S_C.COMMISSION_FLG IN ('H', 'M', 'N', 'O') THEN 'S株' ELSE '単元株' END AS UNIT_S_KBN,
    CASE
        WHEN S_C.HITOKUTEI_TRADE_KBN IN ('1', '6', '9') THEN '一般'
        WHEN S_C.HITOKUTEI_TRADE_KBN IN ('0', '5') THEN '特定'
        WHEN S_C.HITOKUTEI_TRADE_KBN IN ('4', '7') THEN '旧NISA'
        WHEN S_C.HITOKUTEI_TRADE_KBN = 'H' THEN '新NISA'
        ELSE 'その他'
    END AS DEPOSIT_KBN,
    CASE
        WHEN S_C.MARKET_CD = '0' THEN '東証'
        WHEN S_C.MARKET_CD IN ('7', 'X') AND TO_CHAR(S_C.TRADE_EXEC_DATE, 'HH24MI') < '1630' THEN '昼間PTS'
        WHEN S_C.MARKET_CD IN ('7', 'X') THEN '夜間PTS'
        ELSE 'その他市場'
    END AS MARKET_NAME,
    COALESCE(S_T.THEME_NAME, 'テーマ未定義') AS THEME_NAME,
    
    -- 【取引区分判定】PITの信用ポインタの有無で判定
    CASE WHEN P.SAT_EXEC_MAR_LD IS NOT NULL THEN '信用' ELSE '現物' END AS TRADE_TYPE,

    -- 【集計】
    COUNT(DISTINCT H_E.EXECUTION_HK) AS EXEC_COUNT,
    SUM(CASE WHEN S_C.MARKET_CD NOT IN ('7', 'X') THEN S_C.KEIJOU_AMOUNT ELSE S_C.EXEC_AMOUNT END) AS TOTAL_EXEC_AMOUNT,
    SUM(S_C.KEIJOU_COMMISSION) AS TOTAL_FEE
FROM SBI_RAW_VAULT.PIT_EXECUTION_DAILY P
JOIN SBI_RAW_VAULT.LINK_EXECUTION_ACCOUNT L ON P.EXECUTION_ACCOUNT_LK = L.EXECUTION_ACCOUNT_LK
JOIN SBI_RAW_VAULT.HUB_EXECUTION H_E ON L.EXECUTION_HK = H_E.EXECUTION_HK
JOIN SBI_RAW_VAULT.HUB_BRAND H_B ON L.BRAND_HK = H_B.BRAND_HK
JOIN SBI_RAW_VAULT.SAT_EXECUTION_CORE S_C 
    ON P.SAT_EXEC_CORE_LD = S_C.LOAD_DATE 
    AND L.EXECUTION_ACCOUNT_LK = S_C.EXECUTION_ACCOUNT_LK
LEFT JOIN SBI_RAW_VAULT.SAT_THEME_DETAIL S_T 
    ON P.SAT_THE_DET_LD = S_T.LOAD_DATE 
    AND L.BRAND_HK = S_T.THEME_HK
GROUP BY 1,2,3,4,5,6,7,8,9;