CREATE OR REPLACE DYNAMIC TABLE SBI_BUSINESS_VAULT.BV_DAILY_MARGIN_EXECUTION_METRICS
TARGET_LAG = 'DOWNSTREAM'
WAREHOUSE = FINANCE_DEMO_WH
COMMENT = '日次信用約定実績メトリクス'
AS
SELECT
    -- ビジネスキーとしてのハッシュ
    SHA2_BINARY(CONCAT_WS('|', P.SNAPSHOT_DATE, H_E.BUTEN_KOUZA, H_B.BRAND_CD), 256) AS BV_SUMMARY_HK,
    P.SNAPSHOT_DATE AS BASE_DATE,
    H_E.BUTEN_KOUZA AS MKDB_ID,
    H_B.BRAND_CD AS BRAND_CD,
    S_C.BUY_SELL, -- 買い・売りの内訳用に追加

    -- 【信用固有の標準化属性：023ロジック】
    CASE S_C.REPAYMENT_LIMIT -- 属性サテライトより参照
        WHEN '6' THEN '制度'
        WHEN '9' THEN '一般_買い'
        WHEN 'A' THEN '一般_売り短期'
        WHEN 'B' THEN '一般_売り長期'
        WHEN 'C' THEN '一般_売り長期'
        WHEN 'D' THEN '一般_日計り_通常'
        WHEN 'E' THEN '一般_日計り_HYPER'
        ELSE 'コード未定義'
    END AS MARGIN_TYPE, -- 制度／一般／日計り
    CASE S_C.SETTLE_CD
        WHEN '6' THEN '新規'
        WHEN '7' THEN '決済'
        WHEN 'G' THEN '決済'
    END AS OPEN_CLOSE_KBN, -- 新規／決済
    CASE S_C.SETTLE_CD
        WHEN '6' THEN '信用'
        WHEN '7' THEN '信用'
        WHEN 'G' THEN '現引・現渡'
    END AS SETTLE_METHOD, -- 決済方法
    
    -- 【共通属性（現物と統一）】
    CASE
        WHEN S_C.MARKET_CD = '0' THEN '東証'
        WHEN S_C.MARKET_CD IN ('7', 'X') AND TO_CHAR(S_C.TRADE_EXEC_DATE, 'HH24MI') < '1630' THEN '昼間PTS'
        WHEN S_C.MARKET_CD IN ('7', 'X') THEN '夜間PTS'
        ELSE 'その他市場'
    END AS MARKET_NAME,
    CASE
        WHEN S_C.ROUTE = '0' THEN 'PC'
        WHEN S_C.ROUTE = 'A' THEN 'アプリ'
        WHEN S_C.ROUTE = '7' THEN 'スマホ'
        ELSE 'その他'
    END AS TRADE_CHANNEL,
    COALESCE(S_B.STOCK_ETF_KBN, '個別株：その他') AS STOCK_ETF_KBN,

    -- 【集計メトリクス】
    COUNT(DISTINCT H_E.EXECUTION_HK) AS EXEC_COUNT, -- 約定件数（ORDER_ID相当）
    SUM(CASE WHEN S_C.MARKET_CD NOT IN ('7', 'X') THEN S_C.KEIJOU_AMOUNT ELSE S_C.EXEC_AMOUNT END) AS TOTAL_EXEC_AMOUNT
FROM SBI_RAW_VAULT.PIT_EXECUTION_DAILY P
JOIN SBI_RAW_VAULT.LINK_EXECUTION_ACCOUNT L ON P.EXECUTION_ACCOUNT_LK = L.EXECUTION_ACCOUNT_LK
JOIN SBI_RAW_VAULT.HUB_EXECUTION H_E ON L.EXECUTION_HK = H_E.EXECUTION_HK
JOIN SBI_RAW_VAULT.HUB_BRAND H_B ON L.BRAND_HK = H_B.BRAND_HK
-- サテライト結合：信用はSETTLE_CD ('6','7','G') でフィルタ
JOIN SBI_RAW_VAULT.SAT_EXECUTION_CORE S_C 
    ON P.SAT_EXEC_CORE_LD = S_C.LOAD_DATE 
    AND L.EXECUTION_ACCOUNT_LK = S_C.EXECUTION_ACCOUNT_LK
JOIN SBI_RAW_VAULT.SAT_BRAND_DETAIL S_B 
    ON P.SAT_BRD_DET_LD = S_B.LOAD_DATE 
    AND P.BRAND_HK = S_B.BRAND_HK
WHERE S_C.SETTLE_CD IN ('6', '7', 'G') -- 信用取引限定
GROUP BY 1,2,3,4,5,6,7,8,9,10,11;