CREATE OR REPLACE DYNAMIC TABLE SBI_BUSINESS_VAULT.BV_DAILY_TRADE_HISTORY_SUMMARY
TARGET_LAG = 'DOWNSTREAM'
WAREHOUSE = FINANCE_DEMO_WH
COMMENT = '日次取引履歴サマリ（統合PIT対応版）'
AS
SELECT
    SHA2_BINARY(CONCAT_WS('|', TO_VARCHAR(P.SNAPSHOT_DATE), H_A.BUTEN_KOUZA, H_B.BRAND_CD), 256) AS BV_SUMMARY_HK,
    P.SNAPSHOT_DATE AS BASE_DATE,
    H_A.BUTEN_KOUZA AS MKDB_ID,
    H_B.BRAND_CD AS BRAND_CD,

    -- 【属性】
    CASE WHEN S_O.TRADE_SHORT_NAME2 = '端株' THEN 'S株' ELSE '単元株' END AS UNIT_S_KBN,
    CASE WHEN P.SAT_ORD_MAR_LD IS NOT NULL THEN '信用' ELSE '現物' END AS TRADE_TYPE,
    COALESCE(S_B.STOCK_ETF_KBN, '個別株：その他') AS STOCK_ETF_KBN,
    COALESCE(S_B.OLD_MOTHERS_KBN, '旧マザーズ以外') AS OLD_MOTHERS_KBN,

    -- 【集計】
    SUM(CASE WHEN S_O.CANCEL = '1' THEN -1 ELSE 1 END) AS NET_EXEC_COUNT,
    SUM(S_O.PRICE * S_O.QUANTITY) AS TOTAL_TRADE_AMOUNT,
    SUM(S_O.FEE) AS TOTAL_FEE
FROM SBI_RAW_VAULT.PIT_ORDER_DAILY P
JOIN SBI_RAW_VAULT.LINK_ORDER_ACOUNT L ON P.ORDER_ACCOUNT_LK = L.ORDER_ACCOUNT_LK
JOIN SBI_RAW_VAULT.HUB_ACCOUNT H_A ON L.ACCOUNT_HK = H_A.ACCOUNT_HK
JOIN SBI_RAW_VAULT.HUB_BRAND H_B ON L.BRAND_HK = H_B.BRAND_HK
JOIN SBI_RAW_VAULT.SAT_ORDER_CORE S_O 
    ON P.SAT_ORD_CORE_LD = S_O.LOAD_DATE 
    AND L.ORDER_ACCOUNT_LK = S_O.ORDER_ACCOUNT_LK
JOIN SBI_RAW_VAULT.SAT_BRAND_DETAIL S_B 
    ON P.SAT_BRD_DET_LD = S_B.LOAD_DATE 
    AND L.BRAND_HK = S_B.BRAND_HK
WHERE H_A.BRANCH_NO NOT IN ('Z00', 'Z01', 'Z13', 'Z18', 'Z24')
GROUP BY 1,2,3,4,5,6,7,8
HAVING NET_EXEC_COUNT > 0;