CREATE OR REPLACE DYNAMIC TABLE SBI_BUSINESS_VAULT.BV_RE_ACCT_STATUS_DAILY
TARGET_LAG = 'DOWNSTREAM'
WAREHOUSE = FINANCE_DEMO_WH
COMMENT = '口座・銘柄別の国内現物・国内信用・外国現物の取引期間フラット集計'
AS
WITH RAW_DATA AS (
    -- 国内株（現物・信用）
    SELECT
        H_A.BUTEN_KOUZA AS MKDB_ID,
        H_B.BRAND_CD AS BRAND_CD,
        P.SNAPSHOT_DATE,
        S_C.TRADE_EXEC_DATE AS EXEC_DATE,
        CASE WHEN P.SAT_EXEC_MAR_LD IS NOT NULL THEN 'DOM_MARGIN' ELSE 'DOM_CASH' END AS CAT
    FROM SBI_RAW_VAULT.PIT_EXECUTION_DAILY P
    JOIN SBI_RAW_VAULT.LINK_EXECUTION_ACCOUNT L ON P.EXECUTION_ACCOUNT_LK = L.EXECUTION_ACCOUNT_LK
    JOIN SBI_RAW_VAULT.HUB_ACCOUNT H_A ON L.ACCOUNT_HK = H_A.ACCOUNT_HK
    JOIN SBI_RAW_VAULT.HUB_BRAND H_B ON L.BRAND_HK = H_B.BRAND_HK
    JOIN SBI_RAW_VAULT.SAT_EXECUTION_CORE S_C 
        ON P.SAT_EXEC_CORE_LD = S_C.LOAD_DATE 
        AND L.EXECUTION_ACCOUNT_LK = S_C.EXECUTION_ACCOUNT_LK

    --UNION ALL

    -- 外国株（現物）
    --SELECT
    --    H_A.BUTEN_KOUZA AS MKDB_ID,
    --    H_B.BRAND_CD AS BRAND_CD,
    --    P.SNAPSHOT_DATE,
    --    S_F.TRADE_EXEC_DATE AS EXEC_DATE,
    --    'FOR_CASH' AS CAT
    --FROM SBI_RAW_VAULT.PIT_EXECUTION_FOREIGN_DAILY P
    --JOIN SBI_RAW_VAULT.LINK_EXEC_FOREIGN_ACCOUNT L ON P.EXEC_FOREIGN_LK = L.EXEC_FOREIGN_LK
    --JOIN SBI_RAW_VAULT.HUB_ACCOUNT H_A ON L.ACCOUNT_HK = H_A.ACCOUNT_HK
    --JOIN SBI_RAW_VAULT.HUB_BRAND H_B ON L.BRAND_HK = H_B.BRAND_HK
    --JOIN SBI_RAW_VAULT.SAT_EXEC_FOREIGN_CASH S_F 
    --    ON P.SAT_FOR_CORE_LD = S_F.LOAD_DATE 
    --    AND L.EXEC_FOREIGN_LK = S_F.EXEC_FOREIGN_LK
)
SELECT
    -- 一意キー：基準日、口座、銘柄
    SHA2_BINARY(CONCAT_WS('|', TO_VARCHAR(SNAPSHOT_DATE), MKDB_ID, BRAND_CD), 256) AS BV_TIMELINE_HK,
    SNAPSHOT_DATE AS BASE_DATE,
    MKDB_ID,
    BRAND_CD,

    -- 国内現物 (Domestic Cash)
    MIN(CASE WHEN CAT = 'DOM_CASH' THEN EXEC_DATE END) AS DOM_CASH_FIRST_DATE,
    MAX(CASE WHEN CAT = 'DOM_CASH' THEN EXEC_DATE END) AS DOM_CASH_LATEST_DATE,

    -- 国内信用 (Domestic Margin)
    MIN(CASE WHEN CAT = 'DOM_MARGIN' THEN EXEC_DATE END) AS DOM_MARGIN_FIRST_DATE,
    MAX(CASE WHEN CAT = 'DOM_MARGIN' THEN EXEC_DATE END) AS DOM_MARGIN_LATEST_DATE,

    -- 外国現物 (Foreign Cash)
    --MIN(CASE WHEN CAT = 'FOR_CASH' THEN EXEC_DATE END) AS FOR_CASH_FIRST_DATE,
    --MAX(CASE WHEN CAT = 'FOR_CASH' THEN EXEC_DATE END) AS FOR_CASH_LATEST_DATE,

    -- 全体（クロスセグメント）
    MIN(EXEC_DATE) AS TOTAL_FIRST_DATE,
    MAX(EXEC_DATE) AS TOTAL_LATEST_DATE
FROM RAW_DATA
GROUP BY 
    SNAPSHOT_DATE, 
    MKDB_ID, 
    BRAND_CD;