USE ROLE ACCOUNTADMIN;
USE WAREHOUSE TEMP_WH;

SHOW ROLES;
-- ウェアハウスにリソースモニターを割り当てる
ALTER WAREHOUSE FINANCE_DEMO_WH 
SET RESOURCE_MONITOR = FINANCE_DEMO_WH_MONITER;

-- 管理者ロールの作成
CREATE ROLE FINANCE_ADMIN_ROLE;

-- 自分自身（または特定のユーザー）にロールを付与
--SELECT current_user();
--SHOW USERS;
GRANT ROLE FINANCE_ADMIN_ROLE TO USER HIDEAKI_KAWAI;

-- データベースの所有権を移管
GRANT OWNERSHIP ON DATABASE FINANCE_DEMO_DB TO ROLE FINANCE_ADMIN_ROLE COPY CURRENT GRANTS;

-- ウェアハウスの所有権を移管
GRANT OWNERSHIP ON WAREHOUSE FINANCE_DEMO_WH TO ROLE FINANCE_ADMIN_ROLE COPY CURRENT GRANTS;

-- リソースモニターの所有権を移管
GRANT OWNERSHIP ON RESOURCE MONITOR FINANCE_DEMO_WH_MONITER TO ROLE FINANCE_ADMIN_ROLE COPY CURRENT GRANTS;

-- FINANCE_ADMIN_ROLE の権限を SYSADMIN も引き継げるようにする
GRANT ROLE FINANCE_ADMIN_ROLE TO ROLE SYSADMIN;


---確認用
-- これらでリソースが表示されれば成功
USE ROLE FINANCE_ADMIN_ROLE;
SHOW DATABASES LIKE 'FINANCE_DEMO_DB';
SHOW WAREHOUSES LIKE 'FINANCE_DEMO_WH';
SHOW RESOURCE MONITORS LIKE 'FINANCE_DEMO_WH_MONITER';