USE ROLE FINANCE_ADMIN_ROLE;
USE DATABASE FINANCE_DEMO_DB;
USE WAREHOUSE FINANCE_DEMO_WH;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA CORE;
CREATE OR REPLACE SCHEMA SEMANTIC;

--API統合用スキーマ
CREATE OR REPLACE SCHEMA INTEGRATIONS;


--DROP SCHEMA RAW;
--DROP SCHEMA STAGING;
--DROP SCHEMA CORE;
--DROP SCHEMA SEMANTIC;

