USE ROLE ACCOUNTADMIN;
USE DATABASE FINANCE_DEMO_DB;
USE WAREHOUSE FINANCE_DEMO_WH;

ALTER SCHEMA FINANCE_DEMO_DB.RAW SET LOG_LEVEL = 'INFO';
ALTER SCHEMA FINANCE_DEMO_DB.RAW SET TRACE_LEVEL = 'ALWAYS';
ALTER SCHEMA FINANCE_DEMO_DB.RAW SET METRIC_LEVEL = 'ALL';

ALTER SCHEMA FINANCE_DEMO_DB.STAGING SET LOG_LEVEL = 'INFO';
ALTER SCHEMA FINANCE_DEMO_DB.STAGING SET TRACE_LEVEL = 'ALWAYS';
ALTER SCHEMA FINANCE_DEMO_DB.STAGING SET METRIC_LEVEL = 'ALL';


ALTER SCHEMA FINANCE_DEMO_DB.CORE SET LOG_LEVEL = 'INFO';
ALTER SCHEMA FINANCE_DEMO_DB.CORE SET TRACE_LEVEL = 'ALWAYS';
ALTER SCHEMA FINANCE_DEMO_DB.CORE SET METRIC_LEVEL = 'ALL';

ALTER SCHEMA FINANCE_DEMO_DB.SEMANTIC SET LOG_LEVEL = 'INFO';
ALTER SCHEMA FINANCE_DEMO_DB.SEMANTIC SET TRACE_LEVEL = 'ALWAYS';
ALTER SCHEMA FINANCE_DEMO_DB.SEMANTIC SET METRIC_LEVEL = 'ALL';

