-- 管理用テーブルの作成
CREATE OR REPLACE TABLE SBI_RAW_VAULT.CONTROL_SNAPSHOT_DATES (
    SNAPSHOT_DATE DATE PRIMARY KEY
) COMMENT = 'PITテーブル生成用の基準日マスタ';

-- 2025年4月のデータを流し込む（分析対象期間に合わせて調整してください）
--TRUNCATE TABLE SBI_RAW_VAULT.CONTROL_SNAPSHOT_DATES;
INSERT INTO SBI_RAW_VAULT.CONTROL_SNAPSHOT_DATES (SNAPSHOT_DATE)
SELECT 
    DATEADD(day, seq4(), '2026-01-01')
FROM TABLE(GENERATOR(ROWCOUNT => 31));

SELECT * FROM SBI_RAW_VAULT.CONTROL_SNAPSHOT_DATES ORDER BY SNAPSHOT_DATE;