-- 約定ハブテーブル（HUB_EXECUTION）の定義
CREATE OR REPLACE TABLE SBI_RAW_VAULT.HUB_EXECUTION (
    EXECUTION_HK BINARY(64) NOT NULL COMMENT '約定ハッシュキー（店番口座-約定番号）',
    BUTEN_KOUZA VARCHAR(11) NOT NULL COMMENT '店番-口座番号',
    EC_NO INT NOT NULL COMMENT '約定番号', -- NUMBER(6,0)をINTに変更
    LOAD_DATE TIMESTAMP_NTZ(9) COMMENT 'ロード日時',
    RECORD_SOURCE VARCHAR(100) COMMENT 'レコードソース', -- 18から100へ拡張
    
    PRIMARY KEY (EXECUTION_HK)
) COMMENT = '約定ハブ：約定明細のユニークなキーを管理';