
-- 口座ハブテーブル（HUB_ACCOUNT）の定義
CREATE OR REPLACE TABLE SBI_RAW_VAULT.HUB_ACCOUNT (
	ACCOUNT_HK BINARY(64) COMMENT '口座ハッシュキー（店番-口座）',
	BUTEN_KOUZA VARCHAR(11) COMMENT '店番-口座番号（ビジネスキー）',
	BRANCH_NO VARCHAR(11) COMMENT '店番',
	ACCOUNT_NO VARCHAR(11) COMMENT '口座番号',
	LOAD_DATE TIMESTAMP_NTZ(9) COMMENT 'ロード日時',
	RECORD_SOURCE VARCHAR(255) COMMENT 'レコードソース（データ元）',
    
    PRIMARY KEY (ACCOUNT_HK)
) COMMENT = '口座ハブ：全取引チャネルの口座情報を一元管理';