version: 2

models:
  # --- HUB TABLES ---
  - name: hub_account
    description: "顧客口座ハブ。すべての分析の起点となる口座IDを管理。"
    columns:
      - name: account_hk
        tests:
          - unique
          - not_null
      - name: account_id
        tests:
          - not_null

  - name: hub_stock
    description: "銘柄ハブ。国内株・外国株を問わずすべての銘柄コードを管理。"
    columns:
      - name: stock_hk
        tests:
          - unique
          - not_null

  - name: hub_order
    description: "注文ハブ。取引の発生原因となる注文IDを管理。"
    columns:
      - name: order_hk
        tests:
          - unique
          - not_null

  - name: hub_execution
    description: "約定ハブ。成立した取引の結果を管理。"
    columns:
      - name: execution_hk
        tests:
          - unique
          - not_null

  # --- LINK TABLES ---
  - name: link_order_execution
    description: "注文と約定の1:Nリレーションを管理。"
    columns:
      - name: order_execution_lk
        tests:
          - unique
          - not_null
      - name: order_hk
        tests:
          - relationships:
              to: ref('hub_order')
              field: order_hk
      - name: execution_hk
        tests:
          - relationships:
              to: ref('hub_execution')
              field: execution_hk

  - name: link_order_account_stock
    description: "注文の発生元（口座）と対象（銘柄）を固定する3項リンク。"
    columns:
      - name: order_account_stock_lk
        tests:
          - unique
          - not_null
      - name: order_hk
        tests:
          - relationships:
              to: ref('hub_order')
              field: order_hk
      - name: account_hk
        tests:
          - relationships:
              to: ref('hub_account')
              field: account_hk
      - name: stock_hk
        tests:
          - relationships:
              to: ref('hub_stock')
              field: stock_hk

  - name: link_account_transaction
    description: "口座と入出金トランザクションの紐付け。"
    columns:
      - name: account_transaction_lk
        tests:
          - unique
          - not_null
      - name: account_hk
        tests:
          - relationships:
              to: ref('hub_account')
              field: account_hk

  # --- SATELLITE TABLES ---
  - name: sat_stock_details
    description: "銘柄の属性情報の履歴。HashDiffにより重複ロードを防止。"
    columns:
      - name: stock_hk
        tests:
          - relationships:
              to: ref('hub_stock')
              field: stock_hk
      - name: stock_hashdiff
        tests:
          - not_null

  - name: sat_stock_cash_holdings
    description: "現物預り（残高）の推移。snapshot_dateごとに属性を管理。"
    columns:
      - name: holding_hk
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null