version: 2

models:
  # --- HUB Tables ---
  - name: hub_account
    description: "口座ハブ。SHA2_BINARY(256)を使用したBINARY(32)型キー。"
    columns:
      - name: account_hk
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: BINARY

  - name: hub_stock
    description: "銘柄ハブ。"
    columns:
      - name: stock_hk
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: BINARY

  # --- LINK Tables ---
  - name: link_order_account_stock
    description: "注文・口座・銘柄のリンク。複合キーもBINARY(32)。"
    columns:
      - name: order_account_stock_lk
        tests:
          - unique
          - not_null
      - name: order_hk
        tests:
          - not_null
          - relationships:
              to: ref('hub_order') # もしhub_orderがある場合
              field: order_hk
      - name: account_hk
        tests:
          - not_null
          - relationships:
              to: ref('hub_account')
              field: account_hk
      - name: stock_hk
        tests:
          - not_null
          - relationships:
              to: ref('hub_stock')
              field: stock_hk

  # --- SATELLITE Tables ---
  - name: sat_stock_details
    description: "銘柄詳細サテライト。変更検知用HashDiffもBINARY。"
    columns:
      - name: stock_hk
        tests:
          - not_null
          - relationships:
              to: ref('hub_stock')
              field: stock_hk
      - name: stock_hashdiff
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: BINARY

  # --- PIT Tables ---
  - name: pit_account
    description: "口座別PITテーブル。特定時点の有効レコードへのポインタを保持。"
    columns:
      - name: pit_account_hk
        tests:
          - unique
          - not_null
      - name: account_hk
        tests:
          - not_null
          - relationships:
              to: ref('hub_account')
              field: account_hk
      - name: as_of_date
        tests:
          - not_null

      # --- 修正ポイント ---
      # 画像のエラー内容に基づき、SQLでのエイリアス名と完全に一致させます
      - name: customer_load_date 
        description: "sat_customer_detailsへの外部キー（有効開始日）"
        tests:
          - relationships:
              to: ref('sat_customer_details')
              field: load_date

      - name: cash_holding_load_date
        tests:
          - relationships:
              to: ref('sat_stock_cash_holdings')
              field: load_date