USE DATABASE FINANCE_DEMO_DB;
USE SCHEMA RAW;

-- 重複を除いたユニークなマスタに作り替え
CREATE OR REPLACE TABLE STOCK_MASTER AS
SELECT * FROM (
  SELECT *, 
         ROW_NUMBER() OVER (PARTITION BY brand_cd ORDER BY updated_at DESC) as rnum
  FROM STOCK_MASTER
) WHERE rnum = 1;

-- 不要になった一時列を削除
ALTER TABLE STOCK_MASTER DROP COLUMN rnum;