name: dbt_finance_demo
version: 1.0.0
config-version: 2
profile: dbt_finance_demo
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  dbt_finance_demo:
    +materialized: view
