INSERT INTO SBI_RAW_VAULT.SAT_ORDER_CORE
SELECT 
    -- リンクキー生成（Linkテーブルと同一ロジック）
    SHA2_BINARY(concat_ws('|', 
        coalesce(cast(ORDER_HK as string), ''), 
        coalesce(cast(ACCOUNT_HK as string), ''), 
        coalesce(cast(BRAND_HK as string), '')
    ), 256) as ORDER_ACCOUNT_LK,
    ORDER_HASHDIFF,
    CURRENT_TIMESTAMP() as LOAD_DATE,
    RECORD_SOURCE,
    BASE_MONTH,
    BASE_DATE,
    ORDER_NO,
    TRADE_DATE,
    CANCEL,
    SEARCH_TRADE_M_CD,
    TRADE_SHORT_NAME2,
    PRICE,
    QUANTITY,
    FEE
FROM (
    -- 現物注文
    SELECT ORDER_HK, ACCOUNT_HK, BRAND_HK, ORDER_HASHDIFF, RECORD_SOURCE, BASE_MONTH, BASE_DATE, ORDER_NO, TRADE_DATE, CAST(CANCEL_FLG AS STRING) as CANCEL, SEARCH_TRADE_M_CD, TRADE_SHORT_NAME2, PRICE, QUANTITY, FEE 
    FROM sbi_staging.stg_trade_history_test
    UNION ALL
    -- 信用注文
    SELECT ORDER_HK, ACCOUNT_HK, BRAND_HK, ORDER_HASHDIFF, RECORD_SOURCE, BASE_MONTH, BASE_DATE, ORDER_NO, TRADE_DATE, CANCEL, SEARCH_TRADE_M_CD, NULL AS TRADE_SHORT_NAME2, PRICE, QUANTITY, FEE 
    FROM sbi_staging.stg_tmp_tran_trust_stock_test
) src
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_HK ORDER BY LOAD_DATE DESC) = 1;