INSERT INTO SBI_RAW_VAULT.SAT_POSITION_CORE (
    ACCOUNT_POSITION_LK,
    POSITION_HASHDIFF,
    LOAD_DATE,
    RECORD_SOURCE,
    PRICE_MX_REVISE_VALUE,
    EXEC_BASE_BALANCE_T1,
    APPRAISE_AQUIRE_PRICE,
    APPRAISE_MARKET_PRICE,
    APPRAISE_PROFIT_LOSS_PRICE
)
SELECT
    SHA2_BINARY(
        concat_ws('|', 
        coalesce(cast(STG.ACCOUNT_HK as string), ''), 
        coalesce(cast(STG.POSITION_HK as string), ''),
        coalesce(cast(STG.BRAND_HK as string), '')
        ), 256) as ACCOUNT_POSITION_LK,
    -- 属性の変化を検知するためのハッシュ値生成
    SHA2_BINARY(CONCAT_WS('|', 
        TO_VARCHAR(STG.PRICE_MX_REVISE_VALUE), 
        TO_VARCHAR(STG.EXEC_BASE_BALANCE_T1), 
        TO_VARCHAR(STG.APPRAISE_AQUIRE_PRICE), 
        TO_VARCHAR(STG.APPRAISE_MARKET_PRICE), 
        TO_VARCHAR(STG.APPRAISE_PROFIT_LOSS_PRICE)
    ), 256) AS POSITION_HASHDIFF,
    STG.LOAD_DATE,
    STG.RECORD_SOURCE,
    STG.PRICE_MX_REVISE_VALUE,
    STG.EXEC_BASE_BALANCE_T1,
    STG.APPRAISE_AQUIRE_PRICE,
    STG.APPRAISE_MARKET_PRICE,
    STG.APPRAISE_PROFIT_LOSS_PRICE
FROM SBI_STAGING.stg_bl_int_stock_test STG
QUALIFY ROW_NUMBER() OVER (PARTITION BY STG.position_hk ORDER BY LOAD_DATE DESC) = 1;